name: portugal_guide
description: "Guia completo de Portugal para brasileiros"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev ##

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  cupertino_icons: ^1.0.8
  google_fonts: ^5.0.0
  provider: ^6.1.2
  path_provider: ^2.1.2
  flutter_dotenv: ^5.2.1
  dio: ^5.8.0+1
  logger: ^2.5.0
  country_flags: ^3.2.0
  flutter_modular: ^6.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen_runner: ^5.9.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: false
  generate: true
  assets:
    - .env.dev
    - .env.prod
